# serverless.yml
service: event-summary-service

provider:
  name: aws
  runtime: nodejs16.x
  region: us-west-2
  stage: ${opt:stage, "development"}
  lambdaHashingVersion: 20201221

  environment:
    EVENT_SUMMARY_TABLE: ${self:service}-${self:provider.stage}-eventSummaryTable
    INFO_TABLE: ${self:service}-${self:provider.stage}-infoTable
    CACHE_BUCKET: ${self:service}-${self:provider.stage}-cache-bucket

  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Scan
            - dynamodb:PutItem
            - dynamodb:DeleteItem
            - dynamodb:QueryItem
            - dynamodb:BatchWriteItem
          Resource: "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.EVENT_SUMMARY_TABLE}"
        - Effect: Allow
          Action:
            - dynamodb:GetItem
            - dynamodb:PutItem
          Resource: "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.INFO_TABLE}"
        - Effect: Allow
          Action:
            - s3:PutObject
            - s3:GetObject
          Resource: "arn:aws:s3:::${self:provider.environment.CACHE_BUCKET}/*"

functions:
  setEventSummary:
    handler: source/main.setEventSummary
    events:
      - http:
          path: setEventSummary/{key}
          method: post
          cors: true
  getEventSummary:
    handler: source/main.getEventSummary
    events:
      - http:
          path: getEventSummary/{key}
          method: get
          cors: true
  getAllEvents:
    handler: source/main.getAllEvents
    events:
      - http:
          path: getAllEvents
          method: get
          cors: true
  importFromAllData:
    handler: source/main.importFromAllData
    events:
      - http:
          path: importFromAllData
          method: post
          cors: true

resources:
  Resources:
    eventTable:
      Type: AWS::DynamoDB::Table
      Properties:
        BillingMode: PAY_PER_REQUEST
        TableName: ${self:provider.environment.EVENT_SUMMARY_TABLE}
        AttributeDefinitions:
          - AttributeName: key
            AttributeType: S
        KeySchema:
          - AttributeName: key
            KeyType: HASH
    infoTable:
      Type: AWS::DynamoDB::Table
      Properties:
        BillingMode: PAY_PER_REQUEST
        TableName: ${self:provider.environment.INFO_TABLE}
        AttributeDefinitions:
          - AttributeName: key
            AttributeType: S
        KeySchema:
          - AttributeName: key
            KeyType: HASH
    cacheBucket:
      Type: AWS::S3::Bucket
      Properties:
        AccessControl: Private
        BucketName: ${self:provider.environment.CACHE_BUCKET}

plugins:
  - fullstack-serverless

custom:
  fullstack:
    bucketName: deployed-bucket
    distributionFolder: ../client/builds/web
    indexDocument: index.html
